### ISSUE TITLE
Dalvik cache location problems on Cyanogen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [damonkohler/android-scripting#419]
```
User reported the following error on Cyanogen:

#  dalvikvm -classpath ruboto.jar org.jruby.Main -e "puts 'hello'"
Dalvik VM unable to locate class 'org/jruby/Main'
java.lang.NoClassDefFoundError: org.jruby.Main
       at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: org.jruby.Main in loader
dalvik.system.PathClassLoader[ruboto.jar]
       at dalvik.system.PathClassLoader.findClass(PathClassLoader.java:243)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:532)
```

Original issue reported on code.google.com by `damonkoh...@gmail.com` on 6 Sep 2010 at 7:43

**Comment by damonkohler** [comment]
This issue was moved to damonkohler/sl4a#216
