### ISSUE TITLE
ERROR/sl4a.FileUtils:121(2049): Failed to create directory.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [damonkohler/android-scripting#532]
```
What device(s) are you experiencing the problem on?
miumiu 9 (android 2.1)

What firmware version are you running on the device?


What steps will reproduce the problem?
1. install sl4a_r3.apk using adb
2. try to run it
3.

What is the expected output? What do you see instead?
Logcat
03-17 20:19:58.676: VERBOSE/sl4a.FileUtils:119(2049): Creating directory: 
scripts
03-17 20:19:58.676: ERROR/sl4a.FileUtils:121(2049): Failed to create directory.
03-17 20:19:58.676: DEBUG/AndroidRuntime(2049): Shutting down VM
03-17 20:19:58.676: WARN/dalvikvm(2049): threadid=3: thread exiting with 
uncaught exception (group=0x4001b168)
03-17 20:19:58.686: ERROR/AndroidRuntime(2049): Uncaught handler: thread main 
exiting due to uncaught exception
03-17 20:19:58.696: ERROR/AndroidRuntime(2049): java.lang.RuntimeException: 
Unable to start activity 
ComponentInfo{com.googlecode.android_scripting/com.googlecode.android_scripting.
activity.ScriptManager}: java.lang.RuntimeException: Failed to create scripts 
directory.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2496)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2512)
        at android.app.ActivityThread.access$2200(ActivityThread.java:119)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1863)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:123)
        at android.app.ActivityThread.main(ActivityThread.java:4363)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
        at dalvik.system.NativeStart.main(Native Method)
        Caused by: java.lang.RuntimeException: Failed to create scripts directory.
        at com.googlecode.android_scripting.activity.ScriptManager.onCreate(ScriptManager.java:112)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2459)
        ... 11 more


What version of the product are you using? On what operating system?


Please provide any additional information below.

I unmounted the SD just in case 
```

Original issue reported on code.google.com by `scottbur...@gmail.com` on 17 Mar 2011 at 8:23

**Comment by damonkohler** [comment]
This issue was moved to damonkohler/sl4a#159
